export const VITE_JOBS_API_URL = 'VITE_JOBS_API_URL';
export const VITE_LOGIN = 'VITE_LOGIN';
export const VITE_PASSWORD = 'VITE_PASSWORD';
export const VITE_CLIENT_ID = 'VITE_CLIENT_ID';
export const VITE_CLIENT_SECRET = 'VITE_CLIENT_SECRET';
